server:
  port: 8090
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true

rocketmq:
  nameServer: 127.0.0.1:9876
  name-server: 127.0.0.1:9876
  producer:
    group: my-group1
    sendMessageTimeout: 300000

mybatis-plus:
  type-aliases-package: cc.mrbird.febs.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty